@startuml Standart_Context
title Standart Context Diagram

!include ../c4/C4_Context.puml

' ПОЛЬЗОВАТЕЛИ
Person_Ext(Customer, "Customer", "Клиент:\n— Просматривает предложение по депозитам\n— Оформляет заявку на депозит")
Person_Ext(CallCenterParnerUser, "Call-Center (Partner)", "Сотрудник партнёрского кол-центра:\n— Звонит клиенту по заявкам\n— Первичная обработка заявок")
Person(CallCenterUser, "Call-Center", "Сотрудник кол-центра:\n— Звонит клиенту по заявкам\n— Первичная обработка заявок")
Person(BackOfficeDepositUser, "Back-Office (Deposit)", "Сотрудник бэк-фиса (депозит):\n— Обрабатывает заявки\n— Рассчитывает ставки депозита")
Person(BackOfficeCreditUser, "Back-Office (Credit)", "Сотрудник бэк-фиса (кредит):\n— Анализирует кредитные риски по клиенту")
Person(FrontOfficeUser, "Front-Office", "Сотрудник фронт-фиса\n— Идентифицирует клиента\n- Оформляет документы по депозитам")

' ВНЕШНИЕ СИСТЕМЫ
System_Ext(TelecomSystem, "Telecom System", "Телеком-оператор")
System_Ext(CallCenterPartnerSystem, "Call Center (Partner)", "Система партнёрского кол-центра")
System_Ext(CreditHistorySystem, "Credit History", "Бюро кредитных историй")

' ВНУТРЕННИЕ СИСТЕМЫ
System(CallCenterSystem, "Call Center", "Система кол-центра")
System(ABSSystem, "ABS", "Система АБС")
System(DepositProcessingSystem, "Deposit Processing", "Процессинг депозитов")
System(InternetBankSystem, "Internet Bank", "Интернет-банк")
System(SiteSystem, "Site", "Сайт банка")
System(SMSGateway, "SMS Gateway", "СМС-шлюз телеком-оператора")

' ВЗАИМОДЕЙСТВИЯ
Rel(Customer, SiteSystem, "Просмотр депозитов\n и оформление заявок")
Rel(Customer, InternetBankSystem, "Просмотр депозитов\n и оформление заявок")
Rel_U(CallCenterParnerUser, CallCenterPartnerSystem, "Первичная обработка заявок")
Rel_U(CallCenterUser, CallCenterSystem, "Первичная обработка заявок")
Rel_U(BackOfficeDepositUser, ABSSystem, "Обработка заявок и расчёт ставок")
Rel_U(BackOfficeCreditUser, ABSSystem, "Анализ кредитных рисков по клиенту")
Rel_U(FrontOfficeUser, ABSSystem, "Идентификация клиента\nОформление депозита")

Rel(SMSGateway, TelecomSystem, "Отправка СМС")

Rel(DepositProcessingSystem, CallCenterPartnerSystem, "Создание заявки на звонок")
Rel(DepositProcessingSystem, CallCenterSystem, "Создание заявки на звонок")

Rel(ABSSystem, CreditHistorySystem, "Получение данных о клиенте")
Rel(DepositProcessingSystem, SMSGateway, "Отправка уведомлений по заявке")
Rel(InternetBankSystem, SMSGateway, "Отправка СМС для подтверждения операций")

Rel(InternetBankSystem, DepositProcessingSystem, "Создание заявки на депозит")
Rel(DepositProcessingSystem, ABSSystem, "Создание заявки на депозит")
Rel(SiteSystem, DepositProcessingSystem, "Создание заявки на депозит")


@enduml